name: JerrysQuotesDart
description: Dart based version of the JerrysQuotes Bot
version: 1.0.0
homepage: https://jerbb.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  nyxx: ^1.0.2
  nyxx_commander: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
